name: dasaforms
identifier: Dasaforms
component: com_dasaforms
version: 1.0.0
date: May 2015
author:
    name: Rodrigo Spillere
    email: rodrigo.spillere@coffeebeantech.com
    url: http://www.coffeebeantech.com
copyright: 2015 CoffeeBean. All rights reserved.
license: GNU General Public License
description: Component description
default_language: en-GB
database:
    engine: MyISAM
    default_charset: utf8
